### ISSUE TITLE
Lines Quarter Thru Thru miscalculates

### ISSUE THREAD

**Issue by jeffalder** [bradchristie/taminations-flutter#368]
Lines &lt;Anything> Thru (C2) should have the outsides circulate and the centers do the &lt;Anything> Call.
https://www.tamtwirlers.org/taminations/#?level=C-2&animnum=0&animname=LinesPasstheOceanThrufromLines&link=c2/lines_anything_thru&main=ANIMLIST&detail=CALLS&helplink=info/sequencer

From Waves, "Lines Quarter Thru Thru" should, in theory, have the outsides circulate while the centers quarter thru -- which means centers hinge and the new very centers trade. However, this sequence has the centers simply casting off 3/4.

Heads Pass the Ocean
Extend
Lines Quarter Thru Thru

**Comment by bradchristie** [comment]
From RH Waves, Lines Quarter Thru Thru should give an error because the centers are in a LH box.  The correct call is Lines Left Quarter Thru Thru which the program performs correctly.

From RH Waves, Centers Quarter Thru shows the same behavior so the problem is in Quarter Thru rather than Lines <anything> Thru

**Comment by jeffalder** [comment]
As usual, me making claims about things I don't understand.
